# Generated by Django 3.2.19 on 2026-10-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_payment_payment_status_created_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='city',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
