# Generated by Django 3.2.19 on 2026-10-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_theater_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='screen',
            field=models.CharField(default='Screen 1', max_length=50),
        ),
    ]
