# Generated by Django 3.2.19 on 2026-10-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_theater_screen'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ticket_pdf',
            field=models.FileField(blank=True, null=True, upload_to='tickets/'),
        ),
    ]
