# Generated by Django 3.2.19 on 2026-10-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='history_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='history_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
